version: "3.9"
services:
  car-product:
    image: nasfong/car-product:testing
    container_name: car-product
    networks:
      traefik: {}   # for public HTTP routing via Traefik
      proxy: {}     # for internal service aliases
    environment:
      NODE_ENV: production
      # PostgreSQL - using internal alias
      DATABASE_URL: postgres://postgres:your_postgres_password@alias-postgres:5432/postgres?sslmode=disable
      # MinIO Configuration - using internal alias for upload
      MINIO_ENDPOINT: alias-minio-api
      MINIO_PORT: 9000
      MINIO_USE_SSL: false
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: Rening007minio
      MINIO_BUCKET_NAME: car-images
      # MinIO Public URL - for database storage and public access
      MINIO_PUBLIC_URL: https://minio-api.nasfong.site
      # Analytic
      # NEXT_PUBLIC_GA_MEASUREMENT_ID: G-VTVSE157MQ
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 256M
      
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # --- Router ---
      - "traefik.http.routers.car.rule=Host(`zato.nasfong.site`)"
      - "traefik.http.routers.car.entrypoints=websecure"
      - "traefik.http.routers.car.tls.certresolver=letsencrypt"
      # --- Service ---
      - "traefik.http.services.car.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
  proxy:
    external: true